HandsOnLearning/the-project

package.json
=> Added mchiesa to the list of contributors

src/components/Sidebar/components/UserCard/UserCard.test.js
- should render the first name
- should render the email
- should expand when being clicked
- should collapse when being clicked again
=> Add tests for UserCard

src/components/FormattedText/FormattedText.stories.tsx, src/components/FormattedText/FormattedText.tsx
=> Adds color prop for styling to FormattedText component

src/components/Sidebar/SideBar.tsx
=> Add user card to sidebar

src/components/FormattedText/FormattedText.tsx
=> Adds font-size and font-weight to FormattedText css

src/components/FormattedText/FormattedText.stories.tsx, src/components/FormattedText/FormattedText.tsx, src/variables.ts
=> Adds predefined font-weights as a prop for FormattedText component

src/components/FormattedText/FormattedText.tsx
=> Fixes typo in FormattedText fontweight

src/components/Sidebar/components/UserCard/styles.js
=> Fix styling UserCard

src/components/Button/Button.tsx, src/components/Sidebar/SideBar.tsx
=> Add Button to SideBar

src/App.tsx
closes #110 
Add max-width to sidebar to prevent it to be wider than expected
=> Add max-width to SideBar

src/variables.ts
=> Fixed sidebar background color

src/components/FormattedText/FormattedText.stories.tsx, src/components/FormattedText/FormattedText.tsx, src/variables.ts
=> Made size configurable for FormattedText component

src/components/Sidebar/components/SideBarItem/SideBarItem.stories.tsx, src/components/Sidebar/components/SideBarItem/SideBarItem.tsx
=> fix(SideBarItem): Hover color on half of component

src/components/Sidebar/components/ExpandedList/ExpandedList.tsx, src/components/Sidebar/components/UserCard/UserCard.test.js
Improved tests with hints from this article: https://kentcdodds.com/blog/common-mistakes-with-react-testing-library
=> test(UserCard): improve

src/components/Sidebar/components/UserCard/styles.js
=> Makes LinkText white on hover

src/components/Sidebar/components/ExpandedList/ExpandedList.tsx
=> Fixes margin on UserCard ExpandedList

src/components/Sidebar/SideBar.tsx
=> Adds Spacer below UserCard in Sidebar

src/components/Content/Content.tsx, src/components/Sidebar/components/UserCard/UserCard.tsx, src/variables.ts
=> Adds an enum Routes to variables Routing

src/components/Content/Content.tsx, src/components/Sidebar/components/UserCard/UserCard.tsx, src/variables.ts
=> Renames Routes enum to RoutePath

src/components/Menu/Menu.stories.tsx, src/components/Menu/Menu.tsx, src/components/Menu/components/MenuItem.tsx, src/components/Sidebar/Sidebar.tsx
Redo of PR #194 
Closes Issue #192
=> Replaces SideBarItem with MenuItem

src/components/Sidebar/Sidebar.tsx
=> Refactored Sidebar, some minor changes to css and semantics

codecov.yml, package.json
=> Removes incorrect ignore from codecov.yml and adds it to package.json

src/components/AnchorLink/AnchorLink.stories.tsx, src/components/AnchorLink/AnchorLink.tsx, src/components/AnchorLink/components/LinkText.tsx, src/components/Sidebar/Sidebar.test.tsx, src/components/Sidebar/Sidebar.tsx, src/components/Sidebar/components/ExpandedList/ExpandedList.tsx, src/components/Sidebar/components/UserCard/UserCard.test.js, src/components/Sidebar/components/UserCard/UserCard.tsx, src/components/Sidebar/components/UserCard/styles.js
Closes #225 
This adds an AnchorLink and a LinkText component.
AnchorLink takes color as a prop which is black by default but also accepts white.
There's a lot of repitition in something like a menu when you pass color so not sure it's the best approach.
There is also a bug I cannot figure out where UserCard -> ExpandedList does not change to white text on hover. Any help with that would be great. It seems that the default color isn't working, then when you set the AnchorLink to black in UserCard this is added inline and the hover effect doesn't work.
When this is tidied up, next step would be to cater for icons...
=> Adds AnchorLink and LinkText components - WIP

package.json, src/App.test.tsx
=> Added integration test for going to settings

src/components/Label/Label.stories.tsx, src/components/Label/Label.tsx
=> add Label component

src/components/Content/components/ProfileAndSettings/ProfileAndSettings.test.js, src/components/Content/components/ProfileAndSettings/ProfileAndSettings.tsx
Not sure about this. Is it an okey solution? @MoSattler 
Could not find anything about default selected routes
closes #277
=> add Redirect from /settings to /settings/general
